name: Build and Deploy # workflow çš„åç§°
on: [push] # è§¦å‘æ¡ä»¶
permissions:
  contents: write
jobs: # ä»»åŠ¡çš„é›†åˆ
  build-and-deploy: # ä»»åŠ¡çš„åç§°
    runs-on: ubuntu-latest # è¿è¡Œç¯å¢ƒ
    steps: # ä»»åŠ¡çš„æ­¥éª¤
      - name: Checkout ğŸ›ï¸ # æ­¥éª¤çš„åç§°
        uses: actions/checkout@v6 # æ­¥éª¤çš„ä½¿ç”¨çš„ action

      - name: Install and Build ğŸ”§ # è¿è¡Œçš„å‘½ä»¤
        run: |
          npm install -g pnpm
          pnpm install
          pnpm run docs:build

      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs/.vitepress/dist # The folder the action should deploy.
